<a href="https://colab.research.google.com/github/aakarsh-roy/User-Management/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("he")

he


In [ ]:
name = input("enter your name: ");
print(name)

enter your name: aakarsh
aakarsh


In [ ]:
eqn = eval(input("enter eqn: "));
print(eqn)

enter eqn: 2+10
12


In [ ]:
a=10
b=11
c=a
a=b
b=c
print("value of a",a)
print("value of b",b)

value of a 11
value of b 10


In [ ]:
a=12.5
print(type(a))
a=int(a)
print(type(a))
print("a =",a)

<class 'float'>
<class 'int'>
a = 12


In [ ]:
Name=input("Enter your name:")
Class=input("Enter your class:")
print("Id Details")
print("Name: ",Name)
print("Class: ",Class)

Enter your name:Aakarsh
Enter your class:12
Id Details
Name:  Aakarsh
Class:  12


In [ ]:
a=12
print(type(a))
a=float(a)
print(type(a))

<class 'int'>
<class 'float'>


In [ ]:
a=10
b=8
print(a & b)

8


In [ ]:
a =  int(input("enter"))

if a > 10:
  print("HELLO")

print("WOW")




enter5
WOW


In [ ]:
import numpy as np
s = np.array([1, 2, 3, 4, 5, 6])
d = np.array([5])
print(s * d)

[ 5 10 15 20 25 30]


In [ ]:
arr= np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
print (arr[0:2, 0:4])


[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
arr= np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 15, 16]])
print (arr[0, 1:4])
print (arr[1, 0:4])

[2 3 4]
[ 7  8  9 10]


In [ ]:
arr= np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 15, 16]])
print(np.shape(arr))

(2, 6)
